/// The player's mark: one of the game's own balls, in a ring.
///
/// **Generated by default, and a photo only when there genuinely is one.**
/// The generated ball is the design and not a placeholder: it works for an
/// anonymous player, which is most players for most of their first session and
/// the whole point of the anonymous-first flow, and it is made of the game's
/// own objects, so the masthead is furnished with the product rather than a
/// grey silhouette borrowed from a social app.
///
/// A Google account carries a picture, so that account sees its own picture —
/// but the ball remains what every other account gets, and what THIS account
/// gets while the picture is loading or if it never arrives. There is no
/// state in which this widget draws a hole or a spinner.
///
/// **The picture is shown to its owner and to nobody else.** It travels on the
/// session, which is this device's own, and it is not part of a leaderboard
/// row — those carry a name and nothing else, deliberately. A picture shown
/// back to the person it belongs to is not a disclosure; the same picture on a
/// public board is.
///
/// **One ball, not a stack of them.** The first version crammed three into a
/// circle, and at masthead size they were three illegible dots. The glyph is
/// what makes a ball identifiable and a glyph needs room: one ball at a proper
/// size reads, three at a third the size do not.
///
/// The ball is DERIVED from the account id, so it is stable for a player across
/// launches and devices, and differs between two people sitting together. An
/// anonymous player gets one too; it changes if they reinstall, which is an
/// honest reflection of what an anonymous account is.
library;

import 'package:flutter/material.dart';

import '../theme/ball_palette.dart';
import '../theme/tokens.dart';
import 'ball.dart';

class PlayerCrest extends StatelessWidget {
  const PlayerCrest({
    super.key,
    required this.seed,
    this.size = 34,
    this.signedIn = false,
    this.photoUrl,
  });

  /// Whatever identifies this player — the account id, or null while nobody is
  /// known yet.
  final String? seed;

  final double size;

  /// The account's own profile picture, when the provider supplied one.
  ///
  /// Null is the ORDINARY case — anonymous and email accounts have none — so
  /// null renders the generated ball rather than anything apologetic.
  final String? photoUrl;

  /// Draws the rim that marks a real account. Deliberately quiet: the
  /// difference between signed in and not should be legible without being a
  /// badge that nags somebody who has chosen not to be.
  final bool signedIn;

  /// Which ball stands for this player.
  ///
  /// A trivially cheap hash, on purpose — this is decoration, not a key. What
  /// it has to be is STABLE and well spread, so two adjacent uids do not come
  /// out looking like the same person.
  int colorId() {
    final text = seed ?? 'anonymous';
    var h = 0x811C9DC5;
    for (final unit in text.codeUnits) {
      h ^= unit;
      h = (h * 0x01000193) & 0xFFFFFFFF;
    }
    return h % kBallPalette.length;
  }

  @override
  Widget build(BuildContext context) {
    final tokens = PourfectTokens.of(context);

    return Semantics(
      label: signedIn ? 'Your account' : 'Playing as a guest',
      button: true,
      child: Container(
        width: size,
        height: size,
        decoration: BoxDecoration(
          color: tokens.surfaceRaised,
          shape: BoxShape.circle,
          border: Border.all(
            // The rim is the whole signed-in signal, so it uses the cool accent
            // the rest of the app reserves for "this one is current".
            color: signedIn
                ? tokens.accent.withValues(alpha: 0.6)
                : tokens.hairline,
            width: signedIn ? 1.5 : 1,
          ),
        ),
        child: _mark(context),
      ),
    );
  }

  /// The picture if there is one, and the generated ball in every other case.
  Widget _mark(BuildContext context) {
    final url = photoUrl;
    if (url == null || url.isEmpty) return _ball();

    final inset = signedIn ? 1.5 : 1.0;
    return Padding(
      // Inside the rim rather than under it. A circular image drawn to the
      // full diameter hides the border it is supposed to sit within, and the
      // signed-in ring is the entire signed-in signal.
      padding: EdgeInsets.all(inset),
      child: ClipOval(
        child: Image.network(
          url,
          width: size - inset * 2,
          height: size - inset * 2,
          // COVER, so a non-square picture is cropped rather than letterboxed
          // or stretched. Every provider avatar is nominally square and some
          // of them are not.
          fit: BoxFit.cover,
          // A crest is drawn on the first frame of the home screen, so there
          // is no moment at which a spinner would be the right answer. The
          // ball stands in until the bytes arrive, and stays if they never do.
          loadingBuilder: (context, child, progress) =>
              progress == null ? child : _ball(),
          // Offline, a dead URL, a revoked Google picture, a 403 from a
          // rotated CDN link — all of them land here, and all of them mean the
          // same thing to a player: their normal crest.
          errorBuilder: (context, error, stack) => _ball(),
        ),
      ),
    );
  }

  // 0.56 leaves a ring of ground around the ball rather than letting it touch
  // the rim, which at this size reads as a mistake.
  Widget _ball() => Center(child: Ball(colorId: colorId(), size: size * 0.56));
}
